name: Java CI with MySQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 123
          MYSQL_DATABASE: unicorndb
          MYSQL_USER: admin
          MYSQL_PASSWORD: 123
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Start Docker Compose
      run: docker-compose -f docker/ddocker-compose.yaml up --detach
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    

    - name: Run Tests
      run: mvn test

    - name: Stop Docker Compose
      run: docker-compose -f docker/docker-compose.yaml down
